#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Loader-Informix
version:      0.02
version_from: 
installdirs:  site
requires:
    Class::DBI:                    0.89
    Class::DBI::Loader:            0.29
    DBD::Informix:                 2005.02
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
